### ISSUE TITLE
mcr-8 and mcr-9 detection

### ISSUE THREAD

**Issue by minhtrung1997** [liampshaw/mcroni#2]
Hi author,
I'm interesting in your tool as it help me to analysis with more depth mcr-1 gene
Anyway, if only I can also utilize this tool to analyse similarly mcr-8 and mcr-9, and in general, other mcr type. As it matters with the study
Thanks

**Comment by liampshaw** [comment]
Unfortunately not - I'm afraid I'm not familiar with genes like mcr-8 or mcr-9 or how they are mobilised, but e.g. MCR-8.1 has only 31.9% protein identity with MCR-1.1, so I suspect it is different. This is a very specific tool for mcr-1 and associated variants (a list of them is [here](https://github.com/liampshaw/mcroni/blob/main/mcroni/data/mcr1-variants.fa)).

A more general tool for looking at structural variation in genomes that you might find useful is [pangraph](https://github.com/neherlab/pangraph). I am currently working on a pipeline to apply this to the case of gene neighbourhoods with useful visualizations - I'll try to remember to post that here when I have finished it.
